# 1.Print 'Hello HCIA'.

In [1]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a, b = 1, 2
print(a + b)

3


# 3.Define a list and replicate in three different ways.

In [9]:
lst = [1, 2, 3, 4, 5]
print(lst)
print([i for i in lst])
for i in lst:
    print(i, end=' ')

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
1 2 3 4 5 

# 4.Define two lists and merge them together.

In [10]:
lst1 = [1, 2, 3]
lst2 = [4, 5, 6]
print(lst1 + lst2)

[1, 2, 3, 4, 5, 6]


# 5. Get the last element of the list and print it.

In [11]:
lst = [1, 2, 3, 4, 5]
print(lst[-1])

5


# 6.Define a tuple that contains only one element.

In [14]:
tpl = (1)
tpl

1

# 7.Define a three-line long string.

In [15]:
three_line_string = """ this is first line
                        this is second line
                        this is third line"""

# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [18]:
tpl = (1, 2, 3)
for num in tpl:
    print(num, end=' ')

1 2 3 

# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [19]:
def mult(a, b):
    return a * b
mult(8, 6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [21]:
import numpy as np
arr = np.zeros((5, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [22]:
arr = np.zeros((4, 6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [26]:
import numpy as np
arr = np.arange(0, 15, 1)
arr.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [27]:
mtx1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

mtx2 = np.array([[9, 8, 7],
                 [6, 5, 4],
                 [3, 2, 1]])

print(np.dot(mtx1, mtx2))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
